### ISSUE TITLE
Fail on web use. Fail on local use.

### ISSUE THREAD

**Issue by HughP** [stefanocoretta/sfm-exporter#1] opened 2017-02-19 18:15 UTC
my CSV files are failing on the web interface. I do manage to get a return with xlsx files.

I have downloaded the project but when I try to run it in R0Studio I get an error saying that it can't find the 'tools' package. what version of 'tools' are you using? R-Studio says that there is not one for R-Studio version 3.2.3.

**Comment by stefanocoretta** [comment] 2017-02-22 14:08
I couldn't reproduce the issue. Nor on the server neither on the local project. But I noticed another issue meanwhile. I will soon update the code, hopefully this issue will be fixed as well.

**Comment by stefanocoretta** [comment] 2017-06-10 13:18
The problem with `.csv` files in the web interface has been solved. See #2. As for `tools`, everything works with the latest version (3.4.0).

**Closed as completed by stefanocoretta** 2017-06-10 13:18 UTC
Labels: bug
